name: CD

on: 
  push: 
    branches: [ "main" ]

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt/validate
        working-directory: aws
        run: |
          terraform fmt -check
          terraform init -backend=false
          terraform validate